using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Botsy
{
    //The MovieInfo object was created in the Movies.cs file by converting the Json file (which was a big blob of data) into one .NET object.
    //Now that we have the file as an object, we can set some properties with it.
    //To get the autogenerated properites below:  Go to omdb.com, enter a movie, copy the json file and paste special "Paste JSON as classes".
    public class MovieInfo
    {
        public string Title { get; set; }
        public string Year { get; set; }
        public string Rated { get; set; }
        public string Released { get; set; }
        public string Runtime { get; set; }
        public string Genre { get; set; }
        public string Director { get; set; }
        public string Writer { get; set; }
        public string Actors { get; set; }
        public string Plot { get; set; }
        public string Language { get; set; }
        public string Country { get; set; }
        public string Awards { get; set; }
        public string Poster { get; set; }
        public string Metascore { get; set; }
        public string imdbRating { get; set; }
        public string imdbVotes { get; set; }
        public string imdbID { get; set; }
        public string Type { get; set; }
        public string Response { get; set; }
    }
}